name: FITS Black Box Testing
vendor: OPF
maintainer:
  name: Carl Wilson
        email: carl( AT )openplanetsfoundation( DOT )org
  name: Petar Petrov
        email: petar( AT )creativepragmatics( DOT )com
